<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ibu_Model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('ibu');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login');
		}
		else
		{
			$username = $this->input->post('username');
			$password = $this->input->post('password');
			if($username == 'howandi' && $password == 'howandi'){
				$this->session->set_userdata('username', 'howandi');
				$this->session->set_userdata('status', 'admin');
			}
			else{
				$cek_login=$this->Ibu_Model->cek_login(
				$this->input->post('username'),
				$this->input->post('password')
				);
				$this->session->set_userdata('idibu', $cek_login->idibu);
				$this->session->set_userdata('username', $cek_login->username);
				$this->session->set_userdata('status', 'ibu');
			}
			if($this->session->userdata('username'))
			{
				$this->session->set_userdata('logined', true);
				
				redirect('dashboard');
			}
			else 
			{
				$this->session->set_flashdata('gagal','<div class="alert alert-danger"><strong>Gagal Login</strong> Username dan Password Anda Salah.
					</div>');
				redirect("login");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("login");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */